
package mods.fossil.gens.feature;


import java.util.Random;
import mods.fossil.Fossil;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemDoor;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.util.WeightedRandomChestContent;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;
import net.minecraft.world.gen.structure.StructureBoundingBox;
import net.minecraftforge.common.ChestGenHooks;

public class WorldGenHellBoat extends WorldGenerator
{
    
    
	protected Block[] GetValidSpawnBlocks()
	{
		return new Block[]
		{
			Blocks.lava,
		};
	}

	public boolean LocationIsValidSpawn(World world, int x, int y, int z)
	{
		int distanceToAir = 0;
		Block checkBlock = world.getBlock(x, y, z);

		while (checkBlock != Blocks.air)
		{
			distanceToAir++;
			checkBlock = world.getBlock(x, y + distanceToAir, z);
		}

		if (distanceToAir > 1)
		{
			return false;
		}

		y += distanceToAir - 1;

		Block block = world.getBlock(x, y, z);
		Block blockAbove = world.getBlock(x, y + 1, z);
		Block blockBelow = world.getBlock(x, y - 1, z);

		for (Block i : GetValidSpawnBlocks())
		{
			if (blockAbove != Blocks.air)
			{
				return false;
			}
			if (block == i)
			{
				return true;
			}
			else if (block == Blocks.snow_layer && blockBelow == i)
			{
				return true;
			}
			else if (block.getMaterial() == Material.plants && blockBelow == i)
			{
				return true;
			}
		}
		return false;
	}

	public boolean generate(World world, Random rand, int x, int y, int z)
	{
		 generate_r0(world, rand, x, y, z);
       return true;

	}

	public boolean generate_r0(World world, Random rand, int x, int y, int z)
	{
		if(!LocationIsValidSpawn(world, x + 16, y, z + 5))
		{
			return false;
		}

		world.setBlock(x + 4, y + -2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 5, y + -2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 6, y + -2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 7, y + -2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 8, y + -2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 9, y + -2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 10, y + -2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 11, y + -2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 12, y + -2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 13, y + -2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 14, y + -2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 15, y + -2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 16, y + -2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 17, y + -2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 18, y + -2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 19, y + -2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 20, y + -2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 4, y + -1, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 5, y + -1, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 6, y + -1, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 7, y + -1, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 8, y + -1, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 9, y + -1, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 10, y + -1, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 11, y + -1, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 12, y + -1, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 13, y + -1, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 14, y + -1, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 15, y + -1, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 16, y + -1, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 17, y + -1, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 18, y + -1, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 19, y + -1, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 20, y + -1, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 4, y + -1, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 5, y + -1, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 6, y + -1, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 7, y + -1, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 8, y + -1, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 9, y + -1, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 10, y + -1, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 11, y + -1, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 12, y + -1, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 13, y + -1, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 14, y + -1, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 15, y + -1, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 16, y + -1, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 17, y + -1, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 18, y + -1, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 19, y + -1, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 20, y + -1, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 2, y + -1, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 3, y + -1, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 21, y + -1, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 22, y + -1, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 4, y + -1, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 5, y + -1, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 6, y + -1, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 7, y + -1, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 8, y + -1, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 9, y + -1, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 10, y + -1, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 11, y + -1, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 12, y + -1, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 13, y + -1, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 14, y + -1, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 15, y + -1, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 16, y + -1, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 17, y + -1, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 18, y + -1, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 19, y + -1, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 20, y + -1, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 4, y + -1, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 5, y + -1, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 6, y + -1, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 7, y + -1, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 8, y + -1, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 9, y + -1, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 10, y + -1, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 11, y + -1, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 12, y + -1, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 13, y + -1, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 14, y + -1, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 15, y + -1, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 16, y + -1, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 17, y + -1, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 18, y + -1, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 19, y + -1, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 20, y + -1, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 4, y + 0, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 5, y + 0, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 6, y + 0, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 7, y + 0, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 8, y + 0, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 9, y + 0, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 10, y + 0, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 11, y + 0, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 12, y + 0, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 13, y + 0, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 14, y + 0, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 15, y + 0, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 16, y + 0, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 17, y + 0, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 18, y + 0, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 19, y + 0, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 20, y + 0, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 3, y + 0, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 4, y + 0, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 5, y + 0, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 6, y + 0, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 7, y + 0, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 8, y + 0, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 9, y + 0, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 10, y + 0, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 11, y + 0, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 12, y + 0, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 13, y + 0, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 14, y + 0, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 0, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 16, y + 0, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 17, y + 0, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 18, y + 0, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 19, y + 0, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 20, y + 0, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 21, y + 0, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 2, y + 0, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 3, y + 0, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 4, y + 0, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 5, y + 0, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 6, y + 0, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 7, y + 0, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 8, y + 0, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 9, y + 0, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 10, y + 0, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 11, y + 0, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 12, y + 0, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 13, y + 0, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 14, y + 0, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 0, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 16, y + 0, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 17, y + 0, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 18, y + 0, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 19, y + 0, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 20, y + 0, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 21, y + 0, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 22, y + 0, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 1, y + 0, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 2, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 4, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 5, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 6, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 7, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 8, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 9, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 10, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 11, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 12, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 13, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 14, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 16, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 17, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 18, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 19, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 20, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 21, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 22, y + 0, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 23, y + 0, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 24, y + 0, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 2, y + 0, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 3, y + 0, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 4, y + 0, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 5, y + 0, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 6, y + 0, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 7, y + 0, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 8, y + 0, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 9, y + 0, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 10, y + 0, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 11, y + 0, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 12, y + 0, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 13, y + 0, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 14, y + 0, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 0, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 16, y + 0, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 17, y + 0, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 18, y + 0, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 19, y + 0, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 20, y + 0, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 21, y + 0, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 22, y + 0, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 3, y + 0, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 4, y + 0, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 5, y + 0, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 6, y + 0, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 7, y + 0, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 8, y + 0, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 9, y + 0, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 10, y + 0, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 11, y + 0, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 12, y + 0, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 13, y + 0, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 14, y + 0, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 0, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 16, y + 0, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 17, y + 0, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 18, y + 0, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 19, y + 0, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 20, y + 0, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 21, y + 0, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 4, y + 0, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 5, y + 0, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 6, y + 0, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 7, y + 0, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 8, y + 0, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 9, y + 0, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 10, y + 0, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 11, y + 0, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 12, y + 0, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 13, y + 0, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 14, y + 0, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 15, y + 0, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 16, y + 0, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 17, y + 0, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 18, y + 0, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 19, y + 0, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 20, y + 0, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 4, y + 1, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 5, y + 1, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 6, y + 1, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 7, y + 1, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 8, y + 1, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 9, y + 1, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 10, y + 1, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 11, y + 1, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 12, y + 1, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 13, y + 1, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 14, y + 1, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 15, y + 1, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 16, y + 1, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 17, y + 1, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 18, y + 1, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 19, y + 1, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 20, y + 1, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 3, y + 1, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 4, y + 1, z + 2, Fossil.blockSkull, 0, 3);
		world.setBlock(x + 5, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 1, z + 2, Blocks.furnace, 3, 3);
		world.setBlock(x + 10, y + 1, z + 2, Blocks.furnace, 3, 3);
		world.setBlock(x + 11, y + 1, z + 2, Blocks.jukebox, 0, 3);
		world.setBlock(x + 12, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 1, z + 2, Blocks.web, 0, 3);
		world.setBlock(x + 15, y + 1, z + 2, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 16, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 17, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 18, y + 1, z + 2, Blocks.chest, 4, 3);
		 TileEntityChest tileentitychest3 = (TileEntityChest)world.getTileEntity(x + 18, y + 1, z + 2);

	        if (tileentitychest3 != null)
	        {
	            WeightedRandomChestContent.generateChestContents(rand, ChestGenHooks.getItems(Fossil.CHEST_HELLSHIP, rand), tileentitychest3, ChestGenHooks.getCount(Fossil.CHEST_HELLSHIP, rand));
	        }
		world.setBlock(x + 19, y + 1, z + 2, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 20, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 21, y + 1, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 2, y + 1, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 3, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 1, z + 3, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 13, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 1, z + 3, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 16, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 17, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 18, y + 1, z + 3, Blocks.chest, 4, 3);
		 TileEntityChest tileentitychest4 = (TileEntityChest)world.getTileEntity(x + 18, y + 1, z + 3);

	        if (tileentitychest4 != null)
	        {
	            WeightedRandomChestContent.generateChestContents(rand, ChestGenHooks.getItems(Fossil.CHEST_HELLSHIP, rand), tileentitychest4, ChestGenHooks.getCount(Fossil.CHEST_HELLSHIP, rand));
	        }
		world.setBlock(x + 19, y + 1, z + 3, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 20, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 21, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 22, y + 1, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 1, y + 1, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 2, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 1, z + 4, Blocks.chest, 4, 3);
		 TileEntityChest tileentitychest5 = (TileEntityChest)world.getTileEntity(x + 6, y + 1, z + 4);

	        if (tileentitychest5 != null)
	        {
	            WeightedRandomChestContent.generateChestContents(rand, ChestGenHooks.getItems(Fossil.CHEST_HELLSHIP, rand), tileentitychest5, ChestGenHooks.getCount(Fossil.CHEST_HELLSHIP, rand));
	        }
		world.setBlock(x + 7, y + 1, z + 4, Blocks.nether_brick_stairs, 1, 3);
		world.setBlock(x + 8, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 1, z + 4, Blocks.double_stone_slab, 0, 3);
		//world.setBlock(x + 16, y + 1, z + 4, Blocks.iron_door, 3, 3);
        ItemDoor.placeDoorBlock(world, x + 16, y + 1, z + 4, 3, Blocks.iron_door);  

		world.setBlock(x + 17, y + 1, z + 4, Blocks.double_stone_slab, 0, 3);
		world.setBlock(x + 18, y + 1, z + 4, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 19, y + 1, z + 4, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 20, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 21, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 22, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 23, y + 1, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 1, y + 1, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 2, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 1, z + 5, Blocks.nether_brick_stairs, 4, 3);
		world.setBlock(x + 7, y + 1, z + 5, Blocks.nether_brick_stairs, 1, 3);
		world.setBlock(x + 8, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 16, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 17, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 18, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 19, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 21, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 22, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 23, y + 1, z + 5, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 24, y + 1, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 25, y + 1, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 1, y + 1, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 2, y + 1, z + 6, Blocks.web, 0, 3);
		world.setBlock(x + 3, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 1, z + 6, Blocks.chest, 4, 3);
		 TileEntityChest tileentitychest6 = (TileEntityChest)world.getTileEntity(x + 6, y + 1, z + 6);

	        if (tileentitychest6 != null)
	        {
	            WeightedRandomChestContent.generateChestContents(rand, ChestGenHooks.getItems(Fossil.CHEST_HELLSHIP, rand), tileentitychest6, ChestGenHooks.getCount(Fossil.CHEST_HELLSHIP, rand));
	        }
		world.setBlock(x + 7, y + 1, z + 6, Blocks.nether_brick_stairs, 1, 3);
		world.setBlock(x + 8, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 1, z + 6, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 13, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 1, z + 6, Blocks.double_stone_slab, 0, 3);
		//world.setBlock(x + 16, y + 1, z + 6, Blocks.iron_door, 1, 3);
        ItemDoor.placeDoorBlock(world, x + 16, y + 1, z + 6, 3, Blocks.iron_door);  
		world.setBlock(x + 17, y + 1, z + 6, Blocks.double_stone_slab, 0, 3);
		world.setBlock(x + 18, y + 1, z + 6, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 19, y + 1, z + 6, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 20, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 21, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 22, y + 1, z + 6, Blocks.chest, 4, 3);//
        TileEntityChest tileentitychest1 = (TileEntityChest)world.getTileEntity(x + 22, y + 1, z + 6);

        if (tileentitychest1 != null)
        {
            WeightedRandomChestContent.generateChestContents(rand, ChestGenHooks.getItems(Fossil.CHEST_HELLSHIP, rand), tileentitychest1, ChestGenHooks.getCount(Fossil.CHEST_HELLSHIP, rand));
        }
		world.setBlock(x + 23, y + 1, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 2, y + 1, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 3, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 1, z + 7, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 16, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 17, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 19, y + 1, z + 7, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 20, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 21, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 22, y + 1, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 3, y + 1, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 4, y + 1, z + 8, Blocks.anvil, 4, 3);
		world.setBlock(x + 5, y + 1, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 1, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 1, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 1, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 1, z + 8, Blocks.furnace, 2, 3);
		world.setBlock(x + 10, y + 1, z + 8, Blocks.furnace, 2, 3);
		world.setBlock(x + 11, y + 1, z + 8, Blocks.chest, 2, 3);//
		   TileEntityChest tileentitychest2 = (TileEntityChest)world.getTileEntity(x + 11, y + 1, z + 8);

	        if (tileentitychest2 != null)
	        {
	            WeightedRandomChestContent.generateChestContents(rand, ChestGenHooks.getItems(Fossil.CHEST_HELLSHIP, rand), tileentitychest2, ChestGenHooks.getCount(Fossil.CHEST_HELLSHIP, rand));
	        }
		world.setBlock(x + 11, y + 1, z + 7, Blocks.air, 2, 3);

		world.setBlock(x + 12, y + 1, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 1, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 1, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 1, z + 8, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 16, y + 1, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 17, y + 1, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 18, y + 1, z + 8, Blocks.chest, 2, 3);
		 TileEntityChest tileentitychest7 = (TileEntityChest)world.getTileEntity(x + 18, y + 1, z + 8);

	        if (tileentitychest7 != null)
	        {
	            WeightedRandomChestContent.generateChestContents(rand, ChestGenHooks.getItems(Fossil.CHEST_HELLSHIP, rand), tileentitychest7, ChestGenHooks.getCount(Fossil.CHEST_HELLSHIP, rand));
	        }
		world.setBlock(x + 18, y + 1, z + 7, Blocks.air, 2, 3);
		world.setBlock(x + 19, y + 1, z + 8, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 20, y + 1, z + 8, Blocks.web, 0, 3);
		world.setBlock(x + 21, y + 1, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 4, y + 1, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 5, y + 1, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 6, y + 1, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 7, y + 1, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 8, y + 1, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 9, y + 1, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 10, y + 1, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 11, y + 1, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 12, y + 1, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 13, y + 1, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 14, y + 1, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 15, y + 1, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 16, y + 1, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 17, y + 1, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 18, y + 1, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 19, y + 1, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 20, y + 1, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 3, y + 2, z + 1, Blocks.nether_brick_stairs, 4, 3);
		world.setBlock(x + 4, y + 2, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 5, y + 2, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 6, y + 2, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 7, y + 2, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 8, y + 2, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 9, y + 2, z + 1, Fossil.ancientGlass, 0, 3);
		world.setBlock(x + 10, y + 2, z + 1, Fossil.ancientGlass, 0, 3);
		world.setBlock(x + 11, y + 2, z + 1, Fossil.ancientGlass, 0, 3);
		world.setBlock(x + 12, y + 2, z + 1, Fossil.ancientGlass, 0, 3);
		world.setBlock(x + 13, y + 2, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 14, y + 2, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 15, y + 2, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 16, y + 2, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 17, y + 2, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 18, y + 2, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 19, y + 2, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 20, y + 2, z + 1, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 21, y + 2, z + 1, Blocks.nether_brick_stairs, 5, 3);
		world.setBlock(x + 2, y + 2, z + 2, Blocks.nether_brick_stairs, 4, 3);
		world.setBlock(x + 3, y + 2, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 4, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 2, z + 2, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 16, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 17, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 18, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 19, y + 2, z + 2, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 20, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 21, y + 2, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 22, y + 2, z + 2, Blocks.nether_brick_stairs, 5, 3);
		world.setBlock(x + 1, y + 2, z + 3, Blocks.nether_brick_stairs, 4, 3);
		world.setBlock(x + 2, y + 2, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 3, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 2, z + 3, Fossil.skullLantern, 1, 3);
		world.setBlock(x + 13, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 2, z + 3, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 16, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 17, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 18, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 19, y + 2, z + 3, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 20, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 21, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 22, y + 2, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 23, y + 2, z + 3, Blocks.nether_brick_stairs, 5, 3);
		world.setBlock(x + 1, y + 2, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 3, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 2, z + 4, Blocks.nether_brick_stairs, 4, 3);
		world.setBlock(x + 6, y + 2, z + 4, Blocks.nether_brick_stairs, 1, 3);
		world.setBlock(x + 7, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 2, z + 4, Blocks.double_stone_slab, 0, 3);
		world.setBlock(x + 17, y + 2, z + 4, Blocks.double_stone_slab, 0, 3);
		world.setBlock(x + 18, y + 2, z + 4, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 19, y + 2, z + 4, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 20, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 21, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 22, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 23, y + 2, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 24, y + 2, z + 4, Blocks.nether_brick_stairs, 5, 3);
		world.setBlock(x + 1, y + 2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 2, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 2, z + 5, Blocks.nether_brick_stairs, 4, 3);
		world.setBlock(x + 6, y + 2, z + 5, Blocks.nether_brick_stairs, 1, 3);
		world.setBlock(x + 7, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 16, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 17, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 18, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 19, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 21, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 22, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 23, y + 2, z + 5, Fossil.skullLantern, 1, 3);
		world.setBlock(x + 24, y + 2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 25, y + 2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 26, y + 2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 27, y + 2, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 1, y + 2, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 3, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 2, z + 6, Blocks.nether_brick_stairs, 4, 3);
		world.setBlock(x + 6, y + 2, z + 6, Blocks.nether_brick_stairs, 1, 3);
		world.setBlock(x + 7, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 2, z + 6, Fossil.skullLantern, 1, 3);
		world.setBlock(x + 13, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 2, z + 6, Blocks.double_stone_slab, 0, 3);
		world.setBlock(x + 17, y + 2, z + 6, Blocks.double_stone_slab, 0, 3);
		world.setBlock(x + 18, y + 2, z + 6, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 19, y + 2, z + 6, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 20, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 21, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 22, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 23, y + 2, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 24, y + 2, z + 6, Blocks.nether_brick_stairs, 5, 3);
		world.setBlock(x + 1, y + 2, z + 7, Blocks.nether_brick_stairs, 4, 3);
		world.setBlock(x + 2, y + 2, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 3, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 2, z + 7, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 16, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 17, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 18, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 19, y + 2, z + 7, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 20, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 21, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 22, y + 2, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 23, y + 2, z + 7, Blocks.nether_brick_stairs, 5, 3);
		world.setBlock(x + 2, y + 2, z + 8, Blocks.nether_brick_stairs, 4, 3);
		world.setBlock(x + 3, y + 2, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 4, y + 2, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 2, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 2, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 2, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 2, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 2, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 2, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 2, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 2, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 2, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 2, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 2, z + 8, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 16, y + 2, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 17, y + 2, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 18, y + 2, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 19, y + 2, z + 8, Blocks.iron_bars, 0, 3);
		world.setBlock(x + 20, y + 2, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 21, y + 2, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 22, y + 2, z + 8, Blocks.nether_brick_stairs, 5, 3);
		world.setBlock(x + 3, y + 2, z + 9, Blocks.nether_brick_stairs, 4, 3);
		world.setBlock(x + 4, y + 2, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 5, y + 2, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 6, y + 2, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 7, y + 2, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 8, y + 2, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 9, y + 2, z + 9, Fossil.ancientGlass, 0, 3);
		world.setBlock(x + 10, y + 2, z + 9, Fossil.ancientGlass, 0, 3);
		world.setBlock(x + 11, y + 2, z + 9, Fossil.ancientGlass, 0, 3);
		world.setBlock(x + 12, y + 2, z + 9, Fossil.ancientGlass, 0, 3);
		world.setBlock(x + 13, y + 2, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 14, y + 2, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 15, y + 2, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 16, y + 2, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 17, y + 2, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 18, y + 2, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 19, y + 2, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 20, y + 2, z + 9, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 21, y + 2, z + 9, Blocks.nether_brick_stairs, 5, 3);
		world.setBlock(x + 3, y + 3, z + 1, Blocks.nether_brick_stairs, 0, 3);
		world.setBlock(x + 4, y + 3, z + 1, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 5, y + 3, z + 1, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 6, y + 3, z + 1, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 7, y + 3, z + 1, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 8, y + 3, z + 1, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 9, y + 3, z + 1, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 10, y + 3, z + 1, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 11, y + 3, z + 1, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 12, y + 3, z + 1, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 13, y + 3, z + 1, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 14, y + 3, z + 1, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 15, y + 3, z + 1, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 16, y + 3, z + 1, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 17, y + 3, z + 1, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 18, y + 3, z + 1, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 19, y + 3, z + 1, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 20, y + 3, z + 1, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 21, y + 3, z + 1, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 2, y + 3, z + 2, Blocks.nether_brick_stairs, 0, 3);
		world.setBlock(x + 3, y + 3, z + 2, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 4, y + 3, z + 2, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 5, y + 3, z + 2, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 6, y + 3, z + 2, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 7, y + 3, z + 2, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 8, y + 3, z + 2, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 9, y + 3, z + 2, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 10, y + 3, z + 2, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 11, y + 3, z + 2, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 12, y + 3, z + 2, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 13, y + 3, z + 2, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 14, y + 3, z + 2, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 15, y + 3, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 16, y + 3, z + 2, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 17, y + 3, z + 2, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 18, y + 3, z + 2, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 19, y + 3, z + 2, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 20, y + 3, z + 2, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 21, y + 3, z + 2, Blocks.nether_brick_stairs, 1, 3);
		world.setBlock(x + 22, y + 3, z + 2, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 1, y + 3, z + 3, Blocks.nether_brick_stairs, 0, 3);
		world.setBlock(x + 2, y + 3, z + 3, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 3, y + 3, z + 3, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 4, y + 3, z + 3, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 5, y + 3, z + 3, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 6, y + 3, z + 3, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 7, y + 3, z + 3, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 8, y + 3, z + 3, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 9, y + 3, z + 3, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 10, y + 3, z + 3, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 11, y + 3, z + 3, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 12, y + 3, z + 3, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 13, y + 3, z + 3, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 14, y + 3, z + 3, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 15, y + 3, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 16, y + 3, z + 3, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 17, y + 3, z + 3, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 18, y + 3, z + 3, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 19, y + 3, z + 3, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 20, y + 3, z + 3, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 21, y + 3, z + 3, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 22, y + 3, z + 3, Blocks.nether_brick_stairs, 1, 3);
		world.setBlock(x + 23, y + 3, z + 3, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 1, y + 3, z + 4, Blocks.nether_brick_stairs, 0, 3);
		world.setBlock(x + 2, y + 3, z + 4, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 3, y + 3, z + 4, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 4, y + 3, z + 4, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 5, y + 3, z + 4, Blocks.nether_brick_stairs, 1, 3);
		world.setBlock(x + 6, y + 3, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 3, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 3, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 3, z + 4, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 10, y + 3, z + 4, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 11, y + 3, z + 4, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 12, y + 3, z + 4, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 13, y + 3, z + 4, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 14, y + 3, z + 4, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 15, y + 3, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 16, y + 3, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 17, y + 3, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 18, y + 3, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 19, y + 3, z + 4, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 20, y + 3, z + 4, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 21, y + 3, z + 4, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 22, y + 3, z + 4, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 23, y + 3, z + 4, Blocks.nether_brick_stairs, 1, 3);
		world.setBlock(x + 24, y + 3, z + 4, Blocks.nether_brick_stairs, 2, 3);
		world.setBlock(x + 1, y + 3, z + 5, Blocks.nether_brick_stairs, 0, 3);
		world.setBlock(x + 2, y + 3, z + 5, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 3, y + 3, z + 5, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 4, y + 3, z + 5, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 5, y + 3, z + 5, Blocks.nether_brick_stairs, 1, 3);
		world.setBlock(x + 6, y + 3, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 3, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 3, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 3, z + 5, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 10, y + 3, z + 5, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 11, y + 3, z + 5, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 12, y + 3, z + 5, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 13, y + 3, z + 5, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 14, y + 3, z + 5, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 15, y + 3, z + 5, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 16, y + 3, z + 5, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 17, y + 3, z + 5, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 18, y + 3, z + 5, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 19, y + 3, z + 5, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 20, y + 3, z + 5, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 21, y + 3, z + 5, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 22, y + 3, z + 5, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 23, y + 3, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 24, y + 3, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 25, y + 3, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 26, y + 3, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 27, y + 3, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 28, y + 3, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 29, y + 3, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 30, y + 3, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 31, y + 3, z + 5, Blocks.nether_brick_stairs, 5, 3);
		world.setBlock(x + 1, y + 3, z + 6, Blocks.nether_brick_stairs, 0, 3);
		world.setBlock(x + 2, y + 3, z + 6, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 3, y + 3, z + 6, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 4, y + 3, z + 6, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 5, y + 3, z + 6, Blocks.nether_brick_stairs, 1, 3);
		world.setBlock(x + 6, y + 3, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 3, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 3, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 3, z + 6, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 10, y + 3, z + 6, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 11, y + 3, z + 6, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 12, y + 3, z + 6, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 13, y + 3, z + 6, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 14, y + 3, z + 6, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 15, y + 3, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 16, y + 3, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 17, y + 3, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 18, y + 3, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 19, y + 3, z + 6, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 20, y + 3, z + 6, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 21, y + 3, z + 6, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 22, y + 3, z + 6, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 23, y + 3, z + 6, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 24, y + 3, z + 6, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 1, y + 3, z + 7, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 2, y + 3, z + 7, Blocks.nether_brick_stairs, 0, 3);
		world.setBlock(x + 3, y + 3, z + 7, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 4, y + 3, z + 7, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 5, y + 3, z + 7, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 6, y + 3, z + 7, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 7, y + 3, z + 7, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 8, y + 3, z + 7, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 9, y + 3, z + 7, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 10, y + 3, z + 7, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 11, y + 3, z + 7, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 12, y + 3, z + 7, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 13, y + 3, z + 7, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 14, y + 3, z + 7, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 15, y + 3, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 16, y + 3, z + 7, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 17, y + 3, z + 7, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 18, y + 3, z + 7, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 19, y + 3, z + 7, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 20, y + 3, z + 7, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 21, y + 3, z + 7, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 22, y + 3, z + 7, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 23, y + 3, z + 7, Blocks.nether_brick_stairs, 1, 3);
		world.setBlock(x + 2, y + 3, z + 8, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 3, y + 3, z + 8, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 4, y + 3, z + 8, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 5, y + 3, z + 8, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 6, y + 3, z + 8, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 7, y + 3, z + 8, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 8, y + 3, z + 8, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 9, y + 3, z + 8, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 10, y + 3, z + 8, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 11, y + 3, z + 8, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 12, y + 3, z + 8, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 13, y + 3, z + 8, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 14, y + 3, z + 8, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 15, y + 3, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 16, y + 3, z + 8, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 17, y + 3, z + 8, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 18, y + 3, z + 8, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 19, y + 3, z + 8, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 20, y + 3, z + 8, Blocks.stone_slab, 14, 3);
		world.setBlock(x + 21, y + 3, z + 8, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 22, y + 3, z + 8, Blocks.nether_brick_stairs, 1, 3);
		world.setBlock(x + 3, y + 3, z + 9, Blocks.nether_brick_stairs, 0, 3);
		world.setBlock(x + 4, y + 3, z + 9, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 5, y + 3, z + 9, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 6, y + 3, z + 9, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 7, y + 3, z + 9, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 8, y + 3, z + 9, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 9, y + 3, z + 9, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 10, y + 3, z + 9, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 11, y + 3, z + 9, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 12, y + 3, z + 9, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 13, y + 3, z + 9, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 14, y + 3, z + 9, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 15, y + 3, z + 9, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 16, y + 3, z + 9, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 17, y + 3, z + 9, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 18, y + 3, z + 9, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 19, y + 3, z + 9, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 20, y + 3, z + 9, Blocks.nether_brick_stairs, 3, 3);
		world.setBlock(x + 21, y + 3, z + 9, Blocks.nether_brick_stairs, 1, 3);
		world.setBlock(x + 4, y + 4, z + 2, Blocks.obsidian, 0, 3);
		world.setBlock(x + 5, y + 4, z + 2, Blocks.obsidian, 0, 3);
		world.setBlock(x + 6, y + 4, z + 2, Blocks.obsidian, 0, 3);
		world.setBlock(x + 7, y + 4, z + 2, Blocks.obsidian, 0, 3);
		world.setBlock(x + 8, y + 4, z + 2, Blocks.obsidian, 0, 3);
		world.setBlock(x + 9, y + 4, z + 2, Blocks.obsidian, 0, 3);
		world.setBlock(x + 10, y + 4, z + 2, Blocks.obsidian, 0, 3);
		world.setBlock(x + 11, y + 4, z + 2, Blocks.obsidian, 0, 3);
		world.setBlock(x + 12, y + 4, z + 2, Blocks.obsidian, 0, 3);
		world.setBlock(x + 13, y + 4, z + 2, Blocks.obsidian, 0, 3);
		world.setBlock(x + 14, y + 4, z + 2, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 4, z + 2, Blocks.obsidian, 0, 3);
		world.setBlock(x + 16, y + 4, z + 2, Blocks.obsidian, 0, 3);
		world.setBlock(x + 17, y + 4, z + 2, Blocks.obsidian, 0, 3);
		world.setBlock(x + 18, y + 4, z + 2, Blocks.obsidian, 0, 3);
		world.setBlock(x + 19, y + 4, z + 2, Blocks.obsidian, 0, 3);
		world.setBlock(x + 20, y + 4, z + 2, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 4, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 4, y + 4, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 20, y + 4, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 21, y + 4, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 2, y + 4, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 4, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 21, y + 4, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 22, y + 4, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 2, y + 4, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 4, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 11, y + 4, z + 5, Fossil.anuTotem, 5, 3);
		world.setBlock(x + 15, y + 4, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 22, y + 4, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 23, y + 4, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 2, y + 4, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 4, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 21, y + 4, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 22, y + 4, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 4, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 4, y + 4, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 20, y + 4, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 21, y + 4, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 4, y + 4, z + 8, Blocks.obsidian, 0, 3);
		world.setBlock(x + 5, y + 4, z + 8, Blocks.obsidian, 0, 3);
		world.setBlock(x + 6, y + 4, z + 8, Blocks.obsidian, 0, 3);
		world.setBlock(x + 7, y + 4, z + 8, Blocks.obsidian, 0, 3);
		world.setBlock(x + 8, y + 4, z + 8, Blocks.obsidian, 0, 3);
		world.setBlock(x + 9, y + 4, z + 8, Blocks.obsidian, 0, 3);
		world.setBlock(x + 10, y + 4, z + 8, Blocks.obsidian, 0, 3);
		world.setBlock(x + 11, y + 4, z + 8, Blocks.obsidian, 0, 3);
		world.setBlock(x + 12, y + 4, z + 8, Blocks.obsidian, 0, 3);
		world.setBlock(x + 13, y + 4, z + 8, Blocks.obsidian, 0, 3);
		world.setBlock(x + 14, y + 4, z + 8, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 4, z + 8, Blocks.obsidian, 0, 3);
		world.setBlock(x + 16, y + 4, z + 8, Blocks.obsidian, 0, 3);
		world.setBlock(x + 17, y + 4, z + 8, Blocks.obsidian, 0, 3);
		world.setBlock(x + 18, y + 4, z + 8, Blocks.obsidian, 0, 3);
		world.setBlock(x + 19, y + 4, z + 8, Blocks.obsidian, 0, 3);
		world.setBlock(x + 20, y + 4, z + 8, Blocks.obsidian, 0, 3);
		world.setBlock(x + 4, y + 5, z + 2, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 5, y + 5, z + 2, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 6, y + 5, z + 2, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 7, y + 5, z + 2, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 8, y + 5, z + 2, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 9, y + 5, z + 2, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 10, y + 5, z + 2, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 11, y + 5, z + 2, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 12, y + 5, z + 2, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 13, y + 5, z + 2, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 14, y + 5, z + 2, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 15, y + 5, z + 2, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 16, y + 5, z + 2, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 17, y + 5, z + 2, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 18, y + 5, z + 2, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 19, y + 5, z + 2, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 20, y + 5, z + 2, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 3, y + 5, z + 3, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 4, y + 5, z + 3, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 20, y + 5, z + 3, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 21, y + 5, z + 3, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 2, y + 5, z + 4, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 3, y + 5, z + 4, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 21, y + 5, z + 4, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 22, y + 5, z + 4, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 2, y + 5, z + 5, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 3, y + 5, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 5, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 22, y + 5, z + 5, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 23, y + 5, z + 5, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 2, y + 5, z + 6, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 3, y + 5, z + 6, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 21, y + 5, z + 6, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 22, y + 5, z + 6, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 3, y + 5, z + 7, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 4, y + 5, z + 7, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 20, y + 5, z + 7, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 21, y + 5, z + 7, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 4, y + 5, z + 8, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 5, y + 5, z + 8, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 6, y + 5, z + 8, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 7, y + 5, z + 8, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 8, y + 5, z + 8, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 9, y + 5, z + 8, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 10, y + 5, z + 8, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 11, y + 5, z + 8, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 12, y + 5, z + 8, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 13, y + 5, z + 8, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 14, y + 5, z + 8, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 15, y + 5, z + 8, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 16, y + 5, z + 8, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 17, y + 5, z + 8, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 18, y + 5, z + 8, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 19, y + 5, z + 8, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 20, y + 5, z + 8, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 3, y + 6, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 6, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 7, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 7, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 8, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 8, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 9, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 9, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 9, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 9, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 9, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 9, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 9, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 9, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 10, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 10, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 11, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 11, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 12, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 12, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 13, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 13, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 14, z + 0, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 14, z + 1, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 14, z + 1, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 14, z + 2, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 14, z + 2, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 14, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 14, z + 3, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 14, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 14, z + 4, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 14, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 14, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 14, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 14, z + 6, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 14, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 14, z + 7, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 14, z + 8, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 14, z + 8, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 14, z + 9, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 14, z + 9, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 14, z + 10, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 15, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 15, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 3, y + 16, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 16, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 17, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 18, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 15, y + 19, z + 5, Blocks.obsidian, 0, 3);
		world.setBlock(x + 14, y + 20, z + 4, Blocks.nether_brick_stairs, 4, 3);
		world.setBlock(x + 15, y + 20, z + 4, Blocks.nether_brick_stairs, 6, 3);
		world.setBlock(x + 16, y + 20, z + 4, Blocks.nether_brick_stairs, 6, 3);
		world.setBlock(x + 15, y + 20, z + 5, Blocks.nether_brick, 0, 3);
		world.setBlock(x + 16, y + 20, z + 5, Blocks.nether_brick_stairs, 5, 3);
		world.setBlock(x + 14, y + 20, z + 6, Blocks.nether_brick_stairs, 4, 3);
		world.setBlock(x + 15, y + 20, z + 6, Blocks.nether_brick_stairs, 7, 3);
		world.setBlock(x + 16, y + 20, z + 6, Blocks.nether_brick_stairs, 7, 3);
		world.setBlock(x + 14, y + 21, z + 4, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 15, y + 21, z + 4, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 16, y + 21, z + 4, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 16, y + 21, z + 5, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 14, y + 21, z + 6, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 15, y + 21, z + 6, Blocks.nether_brick_fence, 0, 3);
		world.setBlock(x + 16, y + 21, z + 6, Blocks.nether_brick_fence, 0, 3);

		generate_r02_last(world, rand, x, y, z);
		return true;

	}
	public boolean generate_r02_last(World world, Random rand, int x, int y, int z)
	{

		world.setBlock(x + 2, y + 2, z + 4, Blocks.redstone_torch, 1, 3);
		world.setBlock(x + 2, y + 2, z + 6, Blocks.redstone_torch, 1, 3);
		world.setBlock(x + 14, y + 4, z + 5, Blocks.ladder, 4, 3);
		world.setBlock(x + 14, y + 5, z + 5, Blocks.ladder, 4, 3);
		world.setBlock(x + 14, y + 6, z + 5, Blocks.ladder, 4, 3);
		world.setBlock(x + 14, y + 7, z + 5, Blocks.ladder, 4, 3);
		world.setBlock(x + 14, y + 8, z + 5, Blocks.ladder, 4, 3);
		world.setBlock(x + 14, y + 9, z + 5, Blocks.ladder, 4, 3);
		world.setBlock(x + 14, y + 10, z + 5, Blocks.ladder, 4, 3);
		world.setBlock(x + 14, y + 11, z + 5, Blocks.ladder, 4, 3);
		world.setBlock(x + 14, y + 12, z + 5, Blocks.ladder, 4, 3);
		world.setBlock(x + 14, y + 13, z + 5, Blocks.ladder, 4, 3);
		world.setBlock(x + 14, y + 14, z + 5, Blocks.ladder, 4, 3);
		world.setBlock(x + 14, y + 15, z + 5, Blocks.ladder, 4, 3);
		world.setBlock(x + 14, y + 16, z + 5, Blocks.ladder, 4, 3);
		world.setBlock(x + 14, y + 17, z + 5, Blocks.ladder, 4, 3);
		world.setBlock(x + 14, y + 18, z + 5, Blocks.ladder, 4, 3);
		world.setBlock(x + 14, y + 19, z + 5, Blocks.ladder, 4, 3);
		world.setBlock(x + 14, y + 20, z + 5, Blocks.ladder, 4, 3);
		return true;

	}
    
}