package mods.fossil.gens.structure;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;

public class weaponshop
{
    /** Some predefined values for custom hooks that I use in the demo structure */
    public static final int CUSTOM_CHEST = 4097, CUSTOM_DISPENSER = 4098, ITEM_FRAME = 4099, PAINTING = 4100,
                            SPAWN_VILLAGER = 4101, CUSTOM_SKULL = 4102, CUSTOM_SIGNWALL = 4103, CUSTOM_SIGNPOST = 4104, RANDOM_HOLE = 4105;

    /** Start of specific chests; I'll use negative values so as not to conflict with item types and such */
    public static final int CUSTOM_CHEST_1 = -1;

    /** Custom signs */
    public static final int CUSTOM_SIGN_1 = 1;

    public static final int[][][][] blockArrayWeaponShop =
    {
        //This is where all the x, y, z values go (i, j, k). They are broke down by
        //layer. This is how the array works building from x to z and by layer y,
        //then they are finished by removing all the world.setBlock and
        //x, y, z coordinates leaving something like this {Block.getIdFromBlock(Blocks.stone)},
        {
            // y = 0
            {
                //x = 0
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 1
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 2
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.dirt)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 3
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.dirt)},
                {Block.getIdFromBlock(Blocks.dirt)},
                {Block.getIdFromBlock(Blocks.dirt)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 4
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.dirt)},
                {Block.getIdFromBlock(Blocks.dirt)},
                {Block.getIdFromBlock(Blocks.dirt)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 5
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.dirt)},
                {Block.getIdFromBlock(Blocks.dirt)},
                {Block.getIdFromBlock(Blocks.dirt)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 6
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.dirt)},
                {Block.getIdFromBlock(Blocks.dirt)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 7
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.dirt)},
                {Block.getIdFromBlock(Blocks.dirt)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.log)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 8
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.dirt)},
                {Block.getIdFromBlock(Blocks.dirt)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 9
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.dirt)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 10
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 11
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
            }
        },
        {
            //y = 1
            {
                //x = 0
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
            },
            {
                //x = 1
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.oak_stairs), 2},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.oak_stairs), 3},
                {0},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 2
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.chest), 5},
                {Block.getIdFromBlock(Blocks.gravel)},
                {Block.getIdFromBlock(Blocks.gravel)},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.oak_stairs)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 3
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.gravel)},
                {Block.getIdFromBlock(Blocks.gravel)},
                {Block.getIdFromBlock(Blocks.gravel)},
                {0},
                {Block.getIdFromBlock(Blocks.stone_slab), 1},
                {0},
                {Block.getIdFromBlock(Blocks.nether_brick_fence)},
                {Block.getIdFromBlock(Blocks.oak_stairs), 1},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 4
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.gravel)},
                {Block.getIdFromBlock(Blocks.gravel)},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 5
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone_slab), 2},
                {Block.getIdFromBlock(Blocks.gravel)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.nether_brick_fence)},
                {Block.getIdFromBlock(Blocks.oak_stairs)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 6
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.planks)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 7
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.planks)},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.glowstone)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 8
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.fence_gate), 2},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.chest), 2},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 9
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.log)},
                {Block.getIdFromBlock(Blocks.oak_stairs)},
                {Block.getIdFromBlock(Blocks.oak_stairs)},
                {Block.getIdFromBlock(Blocks.oak_stairs)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 10
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 11
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
            }
        },
        {
            //y = 2
            {
                //x = 0
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
            },
            {
                //x = 1
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {0},
                {Block.getIdFromBlock(Blocks.oak_stairs), 2},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.oak_stairs), 2},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
            },
            {
                //x = 2
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.gravel)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
            },
            {
                //x = 3
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.gravel)},
                {Block.getIdFromBlock(Blocks.gravel)},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.nether_brick_fence)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 4
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.oak_stairs)},
                {Block.getIdFromBlock(Blocks.gravel)},
                {Block.getIdFromBlock(Blocks.gravel)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 5
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.nether_brick_fence)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 6
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.planks)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 7
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.log)},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 8
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 9
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.log)},
                {Block.getIdFromBlock(Blocks.oak_stairs)},
                {Block.getIdFromBlock(Blocks.oak_stairs)},
                {Block.getIdFromBlock(Blocks.oak_stairs)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 10
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 11
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
            }
        },
        {
            //y = 3
            {
                //x = 0
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 1
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {0},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
            },
            {
                //x = 2
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.gravel)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.stone_slab), 1},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
            },
            {
                //x = 3
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.redstone_torch), 2},
                {Block.getIdFromBlock(Blocks.gravel)},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.iron_bars)},
                {Block.getIdFromBlock(Blocks.stone_slab), 1},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 4
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {0},
                {Block.getIdFromBlock(Blocks.gravel)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.stone_slab), 1},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 5
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.iron_bars)},
                {Block.getIdFromBlock(Blocks.stone_slab), 1},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 6
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 7
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {0},
                {Block.getIdFromBlock(Blocks.vine), 4},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.log)},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 8
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 9
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.log)},
                {Block.getIdFromBlock(Blocks.oak_stairs)},
                {Block.getIdFromBlock(Blocks.oak_stairs)},
                {Block.getIdFromBlock(Blocks.oak_stairs)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 10
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 11
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
            }
        },
        {
            //y = 4
            {
                //x = 0
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.log)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.log)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
            },
            {
                //x = 1
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.vine), 1},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
            },
            {
                //x = 2
                {Block.getIdFromBlock(Blocks.log)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {0},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.vine), 4},
                {Block.getIdFromBlock(Blocks.fence)},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
            },
            {
                //x = 3
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.vine), 4},
                {Block.getIdFromBlock(Blocks.fence)},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
            },
            {
                //x = 4
                {Block.getIdFromBlock(Blocks.log)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {0},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.vine), 4},
                {Block.getIdFromBlock(Blocks.fence)},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
            },
            {
                //x = 5
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {0},
                {Block.getIdFromBlock(Blocks.fence)},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 6
                {Block.getIdFromBlock(Blocks.log)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.fence)},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 7
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.vine), 4},
                {Block.getIdFromBlock(Blocks.fence)},
                {Block.getIdFromBlock(Blocks.fence)},
                {Block.getIdFromBlock(Blocks.planks)},
                {Block.getIdFromBlock(Blocks.fence)},
                {Block.getIdFromBlock(Blocks.fence)},
                {Block.getIdFromBlock(Blocks.fence)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.log)},
            },
            {
                //x = 8
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.vine), 2},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.fence)},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 9
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.vine), 4},
                {0},
                {Block.getIdFromBlock(Blocks.vine), 8},
                {0},
                {Block.getIdFromBlock(Blocks.planks)},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.log)},
            },
            {
                //x = 10
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 11
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.log)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.log)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.log)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
            }
        },
        {
            //y = 5
            {
                //x = 0
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 1
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone_slab), 1},
                {Block.getIdFromBlock(Blocks.vine), 2},
                {Block.getIdFromBlock(Blocks.vine), 2},
                {Block.getIdFromBlock(Blocks.vine), 1},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
            },
            {
                //x = 2
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.tnt)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone_slab), 2},
                {Block.getIdFromBlock(Blocks.stone_slab), 2},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 3
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.unlit_redstone_torch), 5},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone_slab), 2},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 4
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.tnt)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.stone_slab), 1},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 5
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 6
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone_slab), 1},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.stone_slab), 1},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 7
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.stone_slab), 2},
                {Block.getIdFromBlock(Blocks.stone_slab), 2},
                {Block.getIdFromBlock(Blocks.stone_slab), 2},
                {Block.getIdFromBlock(Blocks.stone_slab), 2},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 8
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.stone_slab), 2},
                {Block.getIdFromBlock(Blocks.stone_slab), 2},
                {Block.getIdFromBlock(Blocks.stone_slab), 2},
                {Block.getIdFromBlock(Blocks.stone_slab), 2},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 9
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.stone_slab), 2},
                {Block.getIdFromBlock(Blocks.stone_slab), 2},
                {Block.getIdFromBlock(Blocks.stone_slab), 2},
                {Block.getIdFromBlock(Blocks.stone_slab), 2},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 10
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.stone_slab), 1},
                {Block.getIdFromBlock(Blocks.stone_slab), 1},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone_slab), 1},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 11
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
            }
        },
        {
            //y = 6
            {
                //x = 0
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 1
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 2
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone_slab), 2},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 3
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone_slab), 2},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 4
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.stone_slab), 2},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.cobblestone)},
            },
            {
                //x = 5
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {Block.getIdFromBlock(Blocks.sandstone)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 6
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 7
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 8
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 9
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 10
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {0},
                {0},
                {0},
                {0},
                {0},
                {Block.getIdFromBlock(Blocks.stone)},
                {0},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
            },
            {
                //x = 11
                {Block.getIdFromBlock(Blocks.cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.mossy_cobblestone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
                {Block.getIdFromBlock(Blocks.stone)},
            }
        }
    };
}